### ISSUE TITLE
Non-downloadable data (scraping)

### ISSUE THREAD

**Issue by BobHarper1** [drkane/find-that-charity#12]
FWIW, we scrape some data from the NI Charity Commission website - data that doesn't appear in the downloadable .csv (e.g. number of volunteers, trustees and employees, regions it operates and free text description of what charity does, how it meets public benefits test and its charitable purposes etc).

Morph.io scraper and data here https://morph.io/BobHarper1/charity-commish-ni

Might be useful for people interested text mining, also could provide more info to this search tool.

**Comment by drkane** [comment]
This looks great. Looks like the morph.io API could be used to get the data, so we could probably integrate it fairly easily.

**Comment by drkane** [comment]
Moved to find-that-charity-scrapers: https://github.com/drkane/find-that-charity-scrapers/issues/2
