### ISSUE TITLE
Org-ID prefixes

### ISSUE THREAD

**Issue by BobHarper1** [drkane/find-that-charity#13]
Hi @drkane 

I think you might be familiar with http://org-id.guide? What I propose is adding the prefixes so that we have org-id format identifiers for the relevant registers appearing on the charity's page and as an object in the reconciliation api.

- Company House: GB-COH-[company number]
- England & Wales: GB-CHC-[CCEW charity number]
- Scotland: GB-SC-[OSCR charity number]
- NI: GB-NIC-[CCNI charity number]

... where those exist.

P.S. great job on getting the finder online.

**Comment by drkane** [comment]
Great idea. Do you think it's best to use them as IDs throughout, or just to display them in the data? Latter is easier but it would be good to try and drive adoption by giving them by default.

CCNI seem to use numbers without a prefix - so it would become `GB-NIC-12345`. But imo OSCR treat the "SC" as part of the number, so they become `GB-SC-SC012345`.
