### ISSUE TITLE
elasticsearch > 2.x on dokku

### ISSUE THREAD

**Issue by drkane** [drkane/find-that-charity#52]
Currently not possible to use elasticsearch versions above 2.x with dokku. See:

 - https://github.com/dokku/dokku-elasticsearch/issues/53
 - https://github.com/dokku/dokku-elasticsearch/pull/64

**Comment by josegonzalez** [comment]
We now support 6.7.1 by default.

**Comment by drkane** [comment]
Now working with latest elasticsearch
