### ISSUE TITLE
Redirect from https://dev.findthatcharity.uk/

### ISSUE THREAD

**Issue by KDuerden** [drkane/find-that-charity#87]
If https://dev.findthatcharity.uk/ is not being updated, either automatically redirect to the main site, or a pop-up be added letting people know to go to https://findthatcharity.uk/

**Comment by drkane** [comment]
What do you think about just deleting https://dev.findthatcharity.uk/ ?  Are there people who are still using it?

**Comment by KDuerden** [comment]
Not sure. We have shared the dev link with a few people before the switch. If the link is dead then hopefully people would come back to us to check?

**Comment by drkane** [comment]
I've switched it off - let's see whether it causes any issues.

**Comment by drkane** [comment]
It's now redirecting from https://dev.findthatcharity.uk/ to https://findthatcharity.uk/ 

Closing this issue - can reopen if there's any problems.
