### ISSUE TITLE
Search box font makes it hard to distinguish between lower case o and 0

### ISSUE THREAD

**Issue by KDuerden** [drkane/find-that-charity#88]
See for example: https://findthatcharity.uk/?q=SCo01234

The search term at the top is a clue but it would be helpful for the search to have more distinction between lower case o and 0.

**Comment by drkane** [comment]
This is a good point. Couple of options available:

 - we can switch to a fixed-width font for the search box
 - try and tweak the existing font to make these clearer (need to check if some of the [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric) options are available for that font

**Comment by drkane** [comment]
![image](https://user-images.githubusercontent.com/1049910/106134023-e8c4da80-615d-11eb-90cf-35336bee8d5b.png)
